platform :ios, '8.1'

def pods
 
pod 'MBProgressHUD', '~> 0.9.2'
pod 'AFNetworking', '~> 3.0.4'
pod 'SDWebImage'
pod 'IQKeyboardManager', '~> 3.3.7'
pod 'YYImage'
end

target 'SmartHome-iOS' do
    pods

end
